owner: open-domains
repo: status

sites:
  - name: is-a-fullstack.dev
    url: https://is-a-fullstack.dev
  - name: is-cool.dev
    url: https://is-cool.dev
  - name: is-local.org
    url: https://is-local.org
  - name: is-not-a.dev
    url: https://is-not-a.dev
  - name: localplayer.dev
    url: https://localplayer.dev

status-website:
  cname: status.open-domains.net
  logoUrl: https://raw.githubusercontent.com/open-domains/website/main/static/logo.svg
  name: Open‑Domains
  introTitle: "**Open‑Domains** — free wildcard subdomains for personal & open‑source projects."
  introMessage: Pick a domain (e.g. `yourname.is-cool.dev`) and just start using it—no signup needed. Powered by GitHub Actions & Cloudflare DNS.
  navbar:
    - title: Status
      href: /
    - title: Domains List
      href: https://open-domains.net
    - title: GitHub
      href: https://github.com/open-domains
